const categoryList = [
    "American restaurant",
    "Argentinian restaurant",
    "Asian fusion restaurant",
    "Asian restaurant",
    "Authentic Japanese restaurant",
    "Bar",
    "Bar & grill",
    "Barbecue restaurant",
    "Beer garden",
    "Bistro",
    "Breakfast restaurant",
    "Cafe",
    "Cantonese restaurant",
    "Chicken restaurant",
    "Chicken wings restaurant",
    "Chinese noodle restaurant",
    "Chinese restaurant",
    "Coffee shop",
    "Delivery Restaurant",
    "European restaurant",
    "Family restaurant",
    "Fast food restaurant",
    "Fine dining restaurant",
    "Food court",
    "French restaurant",
    "French steakhouse restaurant",
    "Fusion restaurant",
    "German restaurant",
    "Greek restaurant",
    "Halal restaurant",
    "Hamburger restaurant",
    "Haute French restaurant",
    "Hawker Stall",
    "Hong Kong Style",
    "Hot dog restaurant",
    "Hot pot restaurant",
    "Indian Muslim Restaurant",
    "Indian restaurant",
    "Indonesian restaurant",
    "Italian restaurant",
    "Japanese restaurant",
    "Korean restaurant",
    "Latin American restaurant",
    "Malaysian restaurant",
    "Mediterranean restaurant",
    "Mexican restaurant",
    "Middle Eastern restaurant",
    "Modern Australian restaurant",
    "Modern European restaurant",
    "Modern French restaurant",
    "Nepalese restaurant",
    "New American restaurant",
    "Nyonya restaurant",
    "Oyster bar restaurant",
    "Pizza restaurant",
    "Polynesian restaurant",
    "Pub",
    "Punjabi restaurant",
    "Ramen restaurant",
    "Restaurant",
    "Seafood restaurant",
    "Singaporean restaurant",
    "Southern Italian restaurant",
    "Spanish restaurant",
    "Steak house",
    "Sushi restaurant",
    "Swiss restaurant",
    "Taco restaurant",
    "Taiwanese restaurant",
    "Takeaways",
    "Tapas restaurant",
    "Tex-Mex restaurant",
    "Thai restaurant",
    "Tonkatsu restaurant",
    "Traditional restaurant",
    "Turkish restaurant",
    "Vegetarian restaurant",
    "Vietnamese restaurant",
    "Western restaurant"
]

const ratingList = [
    "4 to 5",
    "3 to 4",
    "2 to 3",
    "1 to 2",
    "0 to 1"
]

export {categoryList, ratingList}